<a href="https://colab.research.google.com/github/azkaibad/DataProcessing/blob/main/PrepocesingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [40]:
dataset = pd.read_csv('Data Reprocess.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [41]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Spain' nan 82000.0]
 ['France' 35.0 nan]
 ['Germany' nan 59000.0]
 ['Spain' 30.0 45000.0]]


In [42]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No'
 'Yes']


In [43]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [44]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63333.333333333336]
 ['France' 35.0 58000.0]
 ['Spain' 37.63636363636363 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Spain' 37.63636363636363 82000.0]
 ['France' 35.0 63333.333333333336]
 ['Germany' 37.63636363636363 59000.0]
 ['Spain' 30.0 45000.0]]


In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer (transformers = [('encoder', OneHotEncoder(), [0])], remainder='passthrough') 
X = np.array(ct.fit_transform(X))

In [46]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63333.333333333336]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 37.63636363636363 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 37.63636363636363 82000.0]
 [1.0 0.0 0.0 35.0 63333.333333333336]
 [0.0 1.0 0.0 37.63636363636363 59000.0]
 [0.0 0.0 1.0 30.0 45000.0]]


In [47]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [48]:
print(y)

[0 1 0 0 1 1 0 1 0 1 1 0 0 1]


In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [50]:
print(X_train)

[[0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 37.63636363636363 82000.0]
 [0.0 1.0 0.0 40.0 63333.333333333336]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 37.63636363636363 59000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 30.0 45000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 63333.333333333336]
 [1.0 0.0 0.0 35.0 58000.0]]


In [51]:
print(X_test)

[[0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 37.63636363636363 52000.0]]


In [52]:
print(y_train)

[0 1 1 1 0 0 1 1 0 0 1]


In [53]:
print(y_test)

[0 1 0]


In [54]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [55]:
print(X_train)

[[0.0 1.0 0.0 -1.062256466259992 -0.7762290761554894]
 [0.0 0.0 1.0 0.15551645535816186 1.5987234614858072]
 [0.0 1.0 0.0 0.532446169192353 0.015421769724943036]
 [0.0 0.0 1.0 -1.5406672568956956 -1.2851474770786244]
 [0.0 1.0 0.0 0.15551645535816186 -0.35213040871954354]
 [1.0 0.0 0.0 1.170327223373291 0.7505261266139156]
 [0.0 0.0 1.0 -1.062256466259992 -1.539606677540192]
 [1.0 0.0 0.0 0.05403537855664949 0.3264274591779698]
 [0.0 1.0 0.0 2.127148804644698 1.6835431949729964]
 [1.0 0.0 0.0 -0.2649051485338195 0.015421769724943036]
 [1.0 0.0 0.0 -0.2649051485338195 -0.43695014220673273]]


In [56]:
print(X_test)

[[0.0 0.0 1.0 0.213505642101884 -0.18249094174516522]
 [1.0 0.0 0.0 1.8082082775542292 1.3442642610242397]
 [0.0 0.0 1.0 0.15551645535816186 -0.9458685431298678]]
